services:
  minio-client:
    build: .
    container_name: minio-webui
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-client.rule=Host(`minio.lurking.site`)" # change domain
      - "traefik.http.routers.minio-client.entrypoints=websecure"
      - "traefik.http.routers.minio-client.tls.certresolver=cloudflare" 
      - "traefik.http.routers.minio-client.tls=true"
    networks:
      - frontend

networks:
  frontend:
    external: true
